include $(THEOS)/makefiles/common.mk

SUBPROJECTS += brdaemon
SUBPROJECTS += brmock
SUBPROJECTS += brids
SUBPROJECTS += brprefs
SUBPROJECTS += bralert
SUBPROJECTS += brwatchdog

include $(THEOS_MAKE_PATH)/aggregate.mk

