ARCHS = arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = BRPrefs

BRPrefs_FILES = Tweak.xm \
		im_login.xm \
		im_setting.xm \
		../src/Account.m \
		../src/IMAutoLoginHelper.m

include $(THEOS_MAKE_PATH)/tweak.mk
