include $(THEOS)/makefiles/common.mk

SUBPROJECTS += mddaemon
SUBPROJECTS += mdmock
SUBPROJECTS += mdsys
SUBPROJECTS += mdids
SUBPROJECTS += mdprefs
SUBPROJECTS += mdalert
SUBPROJECTS += mdwatchdog

include $(THEOS_MAKE_PATH)/aggregate.mk

