#!/bin/sh

# log
rm -fr /tmp/*.plist
cat /dev/null > /tmp/madrid_std.log
cat /dev/null > /tmp/madrid_err.log

# clear old
killall -9 MDDaemon

# start new
chmod 644 /Library/LaunchDaemons/madrid.plist
chown root:wheel /Library/LaunchDaemons/madrid.plist
launchctl load /Library/LaunchDaemons/madrid.plist

chmod 644 /Library/LaunchDaemons/mdwatchdog.plist
chown root:wheel /Library/LaunchDaemons/mdwatchdog.plist
launchctl load /Library/LaunchDaemons/mdwatchdog.plist

# now respring
killall -9 SpringBoard

exit 0
