#!/bin/sh

launchctl unload /Library/LaunchDaemons/madrid.plist
launchctl stop MDDaemon
launchctl remove MDDaemon


launchctl unload /Library/LaunchDaemons/mdwatchdog.plist
launchctl stop MDWatchdog
launchctl remove MDWatchdog

test -f /Library/nk_biz.plist && rm -f /Library/nk_biz.plist
# test -f /Library/CE_UCRT.pem && rm -f /Library/CE_UCRT.pem

killall -9 MDDaemon
killall -9 MDWatchdog

exit 0
