//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface APNSPackEncoder : NSObject
{
//    id <APNSPackEncoderDelegate> _delegate;
//    struct Encoder *_encoder;
//    struct FrameBuilder *_builder;
//    unsigned long long _maxTableSize;
}

@property(nonatomic) unsigned long long maxTableSize; // @synthesize maxTableSize=_maxTableSize;
//@property(nonatomic) id <APNSPackEncoderDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct FrameBuilder *builder; // @synthesize builder=_builder;
@property(nonatomic) struct Encoder *encoder; // @synthesize encoder=_encoder;
- (void)reset;
- (id)metrics;
- (id)valueTable;
- (id)keyTable;
- (id)errorMessage;
- (int)errorCode;
- (BOOL)hasError;
- (id)copyMessage;
- (void)addBinaryPropertyListWithAttributeId:(unsigned char)arg1 data:(id)arg2 isIndexable:(BOOL)arg3;
- (void)addBooleanWithAttributeId:(unsigned char)arg1 value:(BOOL)arg2;
- (void)addInt64WithAttributeId:(unsigned char)arg1 number:(unsigned long long)arg2 isIndexable:(BOOL)arg3;
- (void)addInt32WithAttributeId:(unsigned char)arg1 number:(unsigned int)arg2 isIndexable:(BOOL)arg3;
- (void)addInt16WithAttributeId:(unsigned char)arg1 number:(unsigned short)arg2 isIndexable:(BOOL)arg3;
- (void)addInt8WithAttributeId:(unsigned char)arg1 number:(unsigned char)arg2 isIndexable:(BOOL)arg3;
- (void)addStringWithAttributId:(unsigned char)arg1 string:(id)arg2 isIndexable:(BOOL)arg3;
- (void)addDataWithAttributeId:(unsigned char)arg1 data:(id)arg2 isIndexable:(BOOL)arg3;
- (void)setCommand:(unsigned char)arg1;
- (void)dealloc;
- (id)initWithMaxTableSize:(unsigned long long)arg1;

@end

