//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class APNSPackDecoder, APNSPackEncoder;

@interface APSProtocolParser : NSObject
//{
//    BOOL _isPackedFormat;
//    APNSPackEncoder *_encoderWrapper;
//    APNSPackDecoder *_decoderWrapper;
//    id <APSProtocolParserDelegate> _delegate;
//}

@property(nonatomic) BOOL isPackedFormat; // @synthesize isPackedFormat=_isPackedFormat;
//@property(nonatomic) id <APSProtocolParserDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id decoder; // @synthesize decoder=_decoderWrapper;
@property(readonly, nonatomic) id encoder; // @synthesize encoder=_encoderWrapper;
- (void)setSerialItemInParameters:(id)arg1 commandID:(unsigned long long)arg2 itemID:(unsigned long long)arg3 itemData:(id)arg4;
- (void)setSerialNumberInParameters:(id)arg1 commandID:(unsigned long long)arg2 itemID:(unsigned long long)arg3 Integer:(long long)arg4;
- (BOOL)_parseSerialMessage:(id)arg1 parameters:(id *)arg2 isInvalid:(char *)arg3 lengthParsed:(unsigned long long *)arg4;
- (BOOL)parseMessage:(id)arg1 parameters:(id *)arg2 isInvalid:(BOOL *)arg3 lengthParsed:(unsigned long long *)arg4;
- (void)APNSPackDecoder:(id)arg1 ReceivedError:(int)arg2;
- (void)APNSPackEncoder:(id)arg1 receivedError:(int)arg2;
- (id)copySetActiveState:(BOOL)arg1 forInterval:(unsigned int)arg2;
- (id)copySetActiveIntervalMessageWithInterval:(unsigned int)arg1;
- (id)copyAppTokenGenerateMessageWithTopicHash:(id)arg1 baseToken:(id)arg2 appId:(unsigned short)arg3;
- (id)copyFlushResponseMessageWithPaddingLength:(unsigned long long)arg1;
- (id)copyFlushMessageWithWantPaddingLength:(unsigned long long)arg1 paddingLength:(unsigned long long)arg2;
- (id)copyMessageWithTopicHash:(id)arg1 identifier:(unsigned long long)arg2 payload:(id)arg3 token:(id)arg4 isPlistFormat:(BOOL)arg5 lastRTT:(id)arg6;
- (id)copyKeepAliveMessageWithMetadata:(id)arg1;
- (id)copyMessageTransportAcknowledgeMessage;
- (id)copyMessageAcknowledgeMessageWithResponse:(long long)arg1 messageId:(id)arg2 token:(id)arg3;
- (id)copyMessageAcknowledgeMessageWithResponse:(long long)arg1 messageId:(id)arg2;
- (id)copyFilterMessageWithEnabledHashes:(id)arg1 ignoredHashes:(id)arg2 opportunisticHashes:(id)arg3 pausedHashes:(id)arg4 token:(id)arg5;

// macos 11.3
- (id)copyFilterMessageWithEnabledHashes:(id)arg1 ignoredHashes:(id)arg2 opportunisticHashes:(id)arg3 nonWakingHashes:(id)x pausedHashes:(id)arg4 token:(id)arg5;


- (id)copyConnectMessageWithToken:(id)arg1 state:(int)arg2 presenceFlags:(unsigned int)arg3 interface:(long long)arg4 activeInterval:(unsigned int)arg5 metadata:(id)arg6 certificate:(id)arg7 nonce:(id)arg8 signature:(id)arg9 redirectCount:(unsigned char)arg10 dnsResolveTimeMilliseconds:(double)arg11 tlsHandshakeTimeMilliseconds:(double)arg12 consecutiveConnectionFailureReason:(id)arg13;

// macos 11.3
-(id)copyConnectMessageWithToken:(id)arg2 state:(int)arg3 presenceFlags:(unsigned int)arg4 certificate:(id)arg5 nonce:(id)arg6 signature:(id)arg7 redirectCount:(unsigned char)arg8 lastConnected:(id)arg9 disconnectReason:(id)arg10;


//macos 12.4

- (id)copyConnectMessageWithToken:(id)arg1 state:(int)arg2 interface:(long long)arg3 activeInterval:(unsigned int)arg4 metadata:(id)arg5 certificate:(id)arg6 nonce:(id)arg7 signature:(id)arg8 redirectCount:(unsigned char)arg9 lastConnected:(id)arg10 disconnectReason:(unsigned int)arg11;

- (id)copyConnectMessageWithToken:(id)arg1 state:(int)arg2 interface:(long long)arg3 activeInterval:(unsigned int)arg4 metadata:(id)arg5 certificate:(id)arg6 nonce:(id)arg7 signature:(id)arg8 redirectCount:(unsigned char)arg9;
- (id)copyConnectMessageWithToken:(id)arg1 interface:(long long)arg2 presenceFlags:(unsigned int)arg3 activeInterval:(unsigned int)arg4 metadata:(id)arg5 certificate:(id)arg6 nonce:(id)arg7 signature:(id)arg8 redirectCount:(unsigned char)arg9 dnsResolveTimeMilliseconds:(double)arg10 tlsHandshakeTimeMilliseconds:(double)arg11 consecutiveConnectionFailureReason:(id)arg12;
- (id)copyConnectMessageWithToken:(id)arg1 interface:(long long)arg2 activeInterval:(unsigned int)arg3 metadata:(id)arg4 certificate:(id)arg5 nonce:(id)arg6 signature:(id)arg7 redirectCount:(unsigned char)arg8 dnsResolveTimeMilliseconds:(double)arg9 tlsHandshakeTimeMilliseconds:(double)arg10 consecutiveConnectionFailureReason:(id)arg11;
- (id)copyConnectMessageWithToken:(id)arg1 state:(int)arg2 presenceFlags:(unsigned int)arg3 certificate:(id)arg4 nonce:(id)arg5 signature:(id)arg6;
- (id)copyConnectMessageWithToken:(id)arg1 state:(int)arg2;
- (void)dealloc;
- (void)setIsPackedFormat:(BOOL)arg1 maxEncoderTableSize:(unsigned long long)arg2 maxDecoderTableSize:(unsigned long long)arg3;

@end

