//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class APSEnvironment, NSData, NSString;

@protocol APSTCPStream <NSObject>
+ (BOOL)isKeepAliveProxySupportedOnSomeInterface;
@property(readonly, nonatomic) NSString *localIPAddress;
@property(nonatomic) BOOL forceKeepAliveProxyInterface;
@property(nonatomic) BOOL requestKeepAliveProxy;
@property(readonly, nonatomic) NSString *serverIPAddress;
@property(readonly, nonatomic) NSString *serverHostname;
@property(readonly, nonatomic) unsigned long long generation;
@property(readonly, copy, nonatomic) NSString *ifname;
@property(nonatomic) BOOL remainsConnectedWhenWWANSuspends;
@property(nonatomic) BOOL isSuspended;
@property(nonatomic) BOOL isConnected;
@property(copy, nonatomic) NSString *cachedIPAddress;
@property(copy, nonatomic) NSString *redirectHostname;
@property(nonatomic) BOOL useAlternatePort;
@property(nonatomic) BOOL forceWWANInterface;
//@property(nonatomic) id <APSTCPStreamDelegate> delegate;
- (BOOL)didPushCauseWake;
- (BOOL)isKeepAliveProxyConfigured;
- (BOOL)isKeepAliveProxySupportedOnSocketInterface;
- (void)holdPowerAssertionUntilStreamQuiesces;
- (NSString *)tcpInfoDescription;
- (BOOL)hasErrorStatus;
- (void)writeDataInBackground:(NSData *)arg1;
- (long long)write:(const char *)arg1 maxLength:(unsigned long long)arg2;
- (id)initWithEnvironment:(APSEnvironment *)arg1;
- (void)close;
- (void)open;
@end

