//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "APSEnvironment.h"
#import "APSTCPStreamDelegate-Protocol.h"
//#import "APSWakeStateChangeAllNotificationsProtocol.h"
//#import "APSWakeStateChangeNotificationProtocol.h"
//#import "NSStreamDelegate.h"

//@class APSEnvironment, APSPowerAssertion, NSDictionary, NSInputStream, NSMutableData, NSObject<OS_dispatch_source>, NSOutputStream, NSString;

@interface APSTCPStream : NSObject </*APSWakeStateChangeNotificationProtocol, APSWakeStateChangeAllNotificationsProtocol,*/ APSTCPStream, NSStreamDelegate>
//{
//    APSEnvironment *_environment;
//    struct OpaqueSecIdentityRef *_clientIdentity;
//    struct _DNSServiceRef_t *_serviceQuery;
//    NSInputStream *_readStream;
//    NSOutputStream *_writeStream;
//    id <APSTCPStreamDelegate> _delegate;
//    BOOL _forceWWANInterface;
//    BOOL _useAlternatePort;
//    BOOL _opened;
//    BOOL _isConnected;
//    BOOL _isSuspended;
//    unsigned long long _generation;
//    NSMutableData *_receiveData;
//    NSMutableData *_sendData;
//    NSString *_peerName;
//    NSString *_serverHostname;
//    NSString *_serverIPAddress;
//    NSString *_redirectHostname;
//    NSString *_cachedIPAddress;
//    BOOL _keepAliveProxyConfigured;
//    BOOL _hasCompletedTLSHandshake;
//    BOOL _peerCertificateIsAuthorized;
//    BOOL _hasSentPresence;
//    BOOL _nagleEnabled;
//    BOOL _closed;
//    BOOL _removedFromRunLoop;
//    BOOL _requestKeepAliveProxy;
//    BOOL _forceKeepAliveProxyInterface;
//    NSString *_localIPAddress;
//    NSString *_interface;
//    NSString *_proxyPropertyName;
//    NSDictionary *_proxyPropertyValue;
//    struct _DNSServiceRef_t *_bonjourSleepProxy;
//    long long _consecutiveKeepAliveProxyRequestFailures;
//    APSPowerAssertion *_requestKeepAliveProxyIfNeededPowerAssertion;
//    APSPowerAssertion *_waitForQuiescentStreamPowerAssertion;
//    NSObject<OS_dispatch_source> *_streamQuiescentCheckTimerSource;
//    BOOL _remainsConnectedWhenWWANSuspends;
//}

+ (BOOL)_interfaceSupportsKeepAliveProxy:(const char *)arg1;
+ (id)firstInterfaceSupportingKeepAliveProxy;
+ (BOOL)isKeepAliveProxyFeatureEnabled;
+ (BOOL)isKeepAliveProxySupportedOnSomeInterface;
+ (unsigned int)cachedServerCountForDomain:(id)arg1;
+ (void)setCachedServerCount:(unsigned int)arg1 forDomain:(id)arg2 ttl:(unsigned int)arg3;
@property(retain, nonatomic) NSString *interface; // @synthesize interface=_interface;
@property(nonatomic) BOOL forceKeepAliveProxyInterface; // @synthesize forceKeepAliveProxyInterface=_forceKeepAliveProxyInterface;
@property(nonatomic) BOOL requestKeepAliveProxy; // @synthesize requestKeepAliveProxy=_requestKeepAliveProxy;
@property(readonly, nonatomic) NSString *localIPAddress; // @synthesize localIPAddress=_localIPAddress;
@property(nonatomic) BOOL remainsConnectedWhenWWANSuspends; // @synthesize remainsConnectedWhenWWANSuspends=_remainsConnectedWhenWWANSuspends;
@property(readonly, nonatomic) unsigned long long generation; // @synthesize generation=_generation;
@property(nonatomic) BOOL useAlternatePort; // @synthesize useAlternatePort=_useAlternatePort;
@property(nonatomic) BOOL forceWWANInterface; // @synthesize forceWWANInterface=_forceWWANInterface;
@property(readonly, nonatomic) NSString *serverIPAddress; // @synthesize serverIPAddress=_serverIPAddress;
@property(readonly, nonatomic) NSString *serverHostname; // @synthesize serverHostname=_serverHostname;
@property(nonatomic) id <APSTCPStreamDelegate> delegate; // @synthesize delegate=_delegate;
- (id)_stringOfInterfaceNameFromSocket:(id)arg1;
- (BOOL)_isKeepAliveProxySupportedOnInterface:(id)arg1;
- (BOOL)isStreamQuiescent;
- (void)_checkIfStreamQuiescent;
- (void)_clearQuiescentCheckTimerSource;
- (void)prepareForFullWake;
- (void)prepareForDarkWake;
- (void)prepareForSleep;
- (void)prepareForWakeStateChange:(id)arg1;
- (void)_clearKeepAliveProxy;
- (void)_configureKeepAliveProxy:(id)arg1;
- (void)_requestKeepAliveProxyIfNeeded;
- (void)_requestKeepAliveProxyIfNeededWithResetFailureCount;
//- (void)_keepAliveProxyErrorCallbackWithServiceRef:(struct _DNSServiceRef_t *)arg1 errorCode:(int)arg2;
- (void)setProxyPropertyName:(id)arg1 value:(id)arg2;
- (BOOL)didPushCauseWake;
- (BOOL)isKeepAliveProxySupportedOnSomeInterface;
- (BOOL)isKeepAliveProxyConfigured;
- (BOOL)isKeepAliveProxySupportedOnSocketInterface;
- (void)holdPowerAssertionUntilStreamQuiesces;
- (id)tcpInfoDescription;
- (void)_hasSpaceAvailable;
- (void)_hasBytesAvailable;
- (id)_copyLocalIPAddressStringForNativeSocket:(id)arg1;
- (id)_copyIPAddressStringForNativeSocket:(id)arg1;
- (BOOL)hasErrorStatus;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)configureWhetherPeerIsTrustedForStream:(id)arg1;
//- (_Bool)isTrust:(struct __SecTrust *)arg1 validWithPolicy:(struct OpaqueSecPolicyRef *)arg2 forPeer:(id)arg3;
- (void)writeDataInBackground:(id)arg1;
- (long long)write:(const char *)arg1 maxLength:(unsigned long long)arg2;
- (void)_connectToServerWithConfiguration:(id)arg1;
- (void)_connectToServerWithCount:(unsigned int)arg1;
- (void)_connectToServerWithPeerName:(id)arg1;
- (void)close;
- (void)_closeQuery;
- (void)_queryRecordReply:(const void *)arg1 length:(unsigned short)arg2 ttl:(unsigned int)arg3 errorCode:(int)arg4;
- (void)_openWithTXTLookup;
- (void)open;
- (Class)configurationClass;
- (id)_domain;
@property(readonly, copy, nonatomic) NSString *ifname;
@property(nonatomic) BOOL isSuspended;
@property(nonatomic) BOOL isConnected;
@property(copy, nonatomic) NSString *cachedIPAddress;
@property(copy, nonatomic) NSString *redirectHostname;
- (void)dealloc;
- (id)initWithEnvironment:(id)arg1;

// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

