//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import "APSTCPStream-Protocol.h"

@class APSConfiguration, NSData, NSDictionary, NSError, NSString;

@protocol APSTCPStreamDelegate <NSObject>
- (void)tcpStreamDidFailToFindKeepAliveProxyInterface:(id <APSTCPStream>)arg1;
- (void)tcpStreamDidFailToObtainKeepAliveProxy:(id <APSTCPStream>)arg1 willRetry:(BOOL)arg2;
- (void)tcpStreamDidFailToForceKeepAliveProxyInterface:(id <APSTCPStream>)arg1;
- (void)tcpStreamDidFailDueToUntrustedPeer:(id <APSTCPStream>)arg1;
- (double)currentKeepAliveInterval;
- (void)tcpStream:(id <APSTCPStream>)arg1 errorOccured:(NSError *)arg2;
- (void)tcpStreamEndEncountered:(id <APSTCPStream>)arg1;
- (unsigned long long)tcpStream:(id <APSTCPStream>)arg1 dataReceived:(NSData *)arg2;
- (unsigned long long)tcpStream:(id <APSTCPStream>)arg1 dataReceived:(NSData *)arg2 isWakingMessage:(BOOL)arg3;

@optional
- (void)tcpStreamHasConnected:(id <APSTCPStream>)arg1 context:(NSDictionary *)arg2 enabledPackedFormat:(BOOL)arg3 maxEncoderTableSize:(unsigned long long)arg4 maxDecoderTableSize:(unsigned long long)arg5 secureHandshakeEnabled:(BOOL)arg6;
- (BOOL)tcpStreamHasSpaceAvailable:(id <APSTCPStream>)arg1;
- (void)tcpStream:(id <APSTCPStream>)arg1 hasDeterminedServerHostname:(NSString *)arg2;
- (void)tcpStream:(id <APSTCPStream>)arg1 receivedServerBag:(APSConfiguration *)arg2;
@end

